### ISSUE TITLE
[New Feature] - Help with automated blocks

### ISSUE THREAD

**Issue by potatoqualitee** [thedavecarroll/BluebirdPS#100]
Hello,
Thank you for this module! I'll be using BlueBirdPS to block abusive users and pile-ons from NBA fans who are targeting my account because they are trying to encode the word ACL. I plan to do this using GitHub Actions 🤩 

Generally, I do the following once I get tagged

* Mute the conversation
* Block the user
* Depending on the tweet (wishing someone would tear their ACL, I may report it as they are trying to evade the rules)

I was happy to see `Set-TwitterBlockedUser`

Edit: Found conversations! 

Also, I'd like to check if anyone that I follow is following the person, and potentially not block them. This could help me with false positives. Is that functionality available, perhaps with `Get-TwitterFriendship`? Edit: Doesn't seem like it.

Edit: Found search! Now I just need notifications.

Thanks again,
Chrissy

**Comment by potatoqualitee** [comment]
btw, notifications can be found here https://api.twitter.com/2/users/2993481/mentions if adding a notification command is on your agenda

**Comment by thedavecarroll** [comment]
## Conversations

Without knowing which endpoint provides access to the `conversation_id`, it would be difficult to ascertain which command would return a Tweet conversation. 

You would have had to taken a leap and assumed one command would have a `Conversation` parameter, and this would have worked to discover the command.

```powershell
Get-Command -Module BluebirdPS | ? {$_.Parameters.Values.Name -match 'conversation'}
```

This yields `Get-Tweet` and further examination would reveal the `ConversationId` parameter.

Behind the scenes, the endpoint being called is `/2/tweets/search/recent` with a specific query for `conversation_id`. Perhaps I should have a completely separate command, like `Get-TweetConversation` that would be more straightforward. _I'll file an issue for this._

From the [documentation](https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-recent)- `The recent search endpoint returns Tweets from the **last seven days** that match a search query.`

It seems that I did not update the command's documentation when switching to v2 endpoint.  _I'll file an issue for this._

## Mentions

To find a command (most) by the Twitter endpoint, use `Get-TwitterApiEndpoint`.

```powershell
Get-TwitterApiEndpoint -Endpoint mentions | Format-List
```
```text
CommandName      : Get-TwitterTimeline
ApiEndpoint      : {GET /2/users/:id/tweets, GET /2/users/:id/mentions}
ApiDocumentation : {https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets,
                   https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-mentions}
```

This should get your mentions.

```powershell
$Mentions = Get-TwitterUser | Get-TwitterTimeline -Mentions
```

From the [documentation](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-mentions) - `Using pagination, up to the most recent 800 Tweets can be retrieved.`

## Friends of Friends

Getting the users that you follow is relatively straightforward, `Get-TwitterFriends`.

Getting the users that your friends follow is not something that can easily be done with the current API endpoints, as the rate limit for the endpoint is 15 calls per 15-minute timespan.

I'll ask in the Twitter Community forum about this.

**Comment by thedavecarroll** [comment]
@potatoqualitee Unless you have any objections, I'm going to close this issue.
