### ISSUE TITLE
[BUG] Search-Tweet - MaxResults not honored

### ISSUE THREAD

**Issue by potatoqualitee** [thedavecarroll/BluebirdPS#101]
**Describe the bug**

When specifying -MaxResults, more comes back than requested.

**To Reproduce**

`Search-Tweet -SearchString "your @cl" -MaxResults 10`

**Expected behavior**
10 results are returned, but 52 are returned (strange number)

**Screenshots**
![2021-06-27_12-52-30](https://user-images.githubusercontent.com/8278033/123541590-a07a0a80-d745-11eb-8307-ad3544772c7b.jpg)

I tested the number from Source and it was 52 as well.

**PowerShell Environment (please complete the following information):**
 - OS: macOS
 - Edition Core
 - Version latest

**Comment by thedavecarroll** [comment]
The `MaxResults` parameter actually specifies the number of results per page.

I thought I had removed this parameter from all commands, but apparently `Search-Tweet` still has it.

It's super confusing, and I apologize for that. I will remove the parameter and set the max_results on the query to the maximum.

**Comment by ebibibi** [comment]
@thedavecarroll 
I understand the MaxResults Option is not limit the result count of  Search-Tweet.
Is there a way to limit result of Search-Tweet?
I'm struggling with too many results now.

**Comment by thedavecarroll** [comment]
@ebibibi I'll look into the feasibility of this.

**Comment by thedavecarroll** [comment]
How does this look? I know this is not the same command, but it would work very similar.

I think for paged operations for individual commands, the command itself would need to have a test if `MaxResults` (which will be renamed to `MaxResultsPerPage`) is less than the max per page, then it would enforce the new `NoPagination` parameter on the `[BluebirdPS.TwitterRequest]' class.

@potatoqualitee @ebibibi 

![image](https://user-images.githubusercontent.com/37391437/184522980-65e3cba7-bd69-441c-8fbc-c7ccdd7e5ac7.png)

**Comment by thedavecarroll** [comment]
Closed by https://github.com/thedavecarroll/BluebirdPS/commit/29c9c700557ca0c7ff3c01d6d1bc34488dac4e77

**Comment by potatoqualitee** [comment]
that works! thank you 🥳
