### ISSUE TITLE
[BUG] Publish-Tweet - Cannot index into a null array

### ISSUE THREAD

**Issue by potatoqualitee** [thedavecarroll/BluebirdPS#110]
this pic describes it all

![image](https://user-images.githubusercontent.com/8278033/124387220-f7e81f80-dcdd-11eb-9019-5b78fe9413cf.png)

**Comment by potatoqualitee** [comment]
Can we get an alias for Send-Tweet to Publish-Tweet 😅

**Comment by alagoutte** [comment]
Hello @potatoqualitee 

Get the same issue... and coming from Oauth (1 or 2) is not enable on my account (needed for write/publish tweet)

**Comment by thedavecarroll** [comment]
@potatoqualitee I assume this is still an issue. Can you provide the full list of parameters that will reproduce the error? Thanks.

**Comment by potatoqualitee** [comment]
I assume too 😅  in this case, it's just

```
Publish-Tweet -TweetText "New release! Check out the release notes"
```

with the api key and all that set with env vars

**Comment by thedavecarroll** [comment]
@potatoqualitee So, this is what I get.
![image](https://user-images.githubusercontent.com/37391437/184797065-c5d6ea10-836f-437b-a360-250dd45afdc2.png)

@alagoutte Could you provide a way to replicate this?

If I can't replicate, I may just close this issue. We can always open a new one if it crops up again.

**Comment by alagoutte** [comment]
Coming from new account… don’t supportv1 API (only v2), need to upgrade account to get v1 (verify account API if remember)

easy to replicate ! Create a new account and enable API !

**Comment by potatoqualitee** [comment]
ohhh now i get it, thank you, @alagoutte !

**Comment by thedavecarroll** [comment]
Hopefully by handling the underlying issues correctly, the user will have some direction on how to mitigate this issue.

In the upcoming release, BluebirdPS will provide better exception handling. Here are some examples.

`Publish-Tweet` is a v2 endpoint.

![AccessTokenPermissionIssue-Publish-Tweet](https://user-images.githubusercontent.com/37391437/184911538-a2ea109c-2f1f-408d-a669-0bd26fc12196.png)

The access level will also be addressed.

`Add-TwitterSavedSearch` is a v1.1 endpoint.

![AccessLevelIssue-Add-TwitterSavedSearch](https://user-images.githubusercontent.com/37391437/184911976-edb30e00-4260-445d-b746-c7f75a01da4a.png)

Essential access does allow access to v2 endpoints, but OAuth 1.0a must be used.

I tested this using a new account with Essential only access.
![BluebirdPS-Testing_AccessLevel](https://user-images.githubusercontent.com/37391437/184914117-a9c5a6e3-6462-4160-88b1-1c7209dc46e2.png)
![BluebirdPS dev_AppAuthSettings](https://user-images.githubusercontent.com/37391437/184914142-df1147e0-d26f-4564-a717-998b8ee6d551.png)
![BluebirdPS-Testing_Project_BluebirdPS dev_KeyTokens](https://user-images.githubusercontent.com/37391437/184914190-1fc6937e-9e20-49df-8ae9-3544c8a39ff9.png)

**Comment by thedavecarroll** [comment]
Possibly fixed via the above documentation or change from v1.1 to v2 `Publish-Tweet`.

**Comment by potatoqualitee** [comment]
ayyy ty
