### ISSUE TITLE
[BUG] Find-TwitterMastodonLinks - Incorrect parsing

### ISSUE THREAD

**Issue by potatoqualitee** [thedavecarroll/BluebirdPS#188]
**Describe the bug**
Some Mastodon addresses don't quite work work

**To Reproduce**
Try to find a mastodon address from the following users

https://twitter.com/alexandair (actual: @alexandair@infosec.exchange) | result: @alex@dair-community)
https://twitter.com/jandedobbeleer (actual: @jan@social.ohmyposh.dev | result: @jan@social.ohmyposh)
https://twitter.com/madebygps (actual: http://hachyderm.io/web/@gps | result: @gps@hachyderm.io/web)
https://twitter.com/justinjbird7 (actual: data-folks.masto.host/@justinjbird | result: @justinjbird@folks.masto.host)

Alexandair and Jan have emojis in their name. Maybe that's why? But justin doesn't have an emoji.

Also, I've noticed a few that broke with madebygp's issue. It is a valid mastodon address with that /web/.

**Expected behavior**
handles it

**PowerShell Environment (please complete the following information):**
GitHub Runner ubuntu-latest

**Additional context**

https://github.com/potatoqualitee/influx/actions/runs/3543655833/jobs/5950338108

**Comment by potatoqualitee** [comment]
Oh, also https://twitter.com/janfishankhan (actual: @janfishankhan@bbq.snoot.com | result: @janfishankhan@bbq.snoot)

**Comment by thedavecarroll** [comment]
Closed via #190
