### ISSUE TITLE
[DISCUSSION]

### ISSUE THREAD

**Issue by ray32245mv** [thedavecarroll/BluebirdPS#195]
![PS_Error](https://user-images.githubusercontent.com/26298465/204107167-a49046f4-4ca7-4d03-b267-9a6778c4f254.png)

Hi Dave,
I'm pretty green with PS (and programming in general), got interested in this as a way to get a better idea of what's going on under-the-hood when I communicate with Twitter. I've got a dev acct set up and have successfully used the "get tweet" endpoint with Postman, and curl from the cli, so I know my creds are good. I have tried to save them with your "set-twitterauth.." every way I can think of and it's just not working. I'm on PS 7, your module downloaded fine. I've included an image here of the errors. Can't figure our what I'm getting wrong..

**Comment by thedavecarroll** [comment]
@ray32245mv 
`Set-TwitterAuthentication` should be used without parameters. It will prompt you for each value.

`Set-TwitterBearerToken` only works after authentication has been configured (as above) and it does not have any parameters (other than the common parameters like Verbose, ErrorAction, etc).

Try those and let me know how it goes.

**Comment by ray32245mv** [comment]
Ahh ok. got the creds in. now, on the bearer token...
Set-TwitterAuthentication did not prompt for bearer token, but Test-TwitterAuthentication shows "True", and Get-Tweet works so do I need to do anything at all with my bearer token?

**Comment by thedavecarroll** [comment]
Once `Set-TwitterAuthentication` has validate the main credentials, it uses that info to get the bearer token. Sounds like you've got it working.

There will be a new release (small, with 1 bugfix) later tonight.

**Comment by ray32245mv** [comment]
Ok, I see now. Thanks for the help, and this module. Looking forward to learning more about it.
