### ISSUE TITLE
Set-TwitterBearerToken: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.

### ISSUE THREAD

**Issue by Saved-by-Him** [thedavecarroll/BluebirdPS#205]
### What is broken or not working?

BluebirdPS\Set-TwitterAuthentication
API Key: *************************
API Secret: **************************************************
Access Token: **************************************************
Access Token Secret: *********************************************
**Set-TwitterBearerToken: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.**

### PowerShell Environment

```shell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 6.1.7601 Service Pack 1
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### What steps will reproduce the behavior?

PS C:\> BluebirdPS\Set-TwitterAuthentication

### Relevant console output

```shell
**Set-TwitterBearerToken: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.**
```

**Comment by thedavecarroll** [comment]
@Saved-by-Him 
Given the age of the OS, you should ensure it is capable and configured to use TLS 1.2.

You can use the following to see what your .NET environment supports.

```powershell
[enum]::GetNames([Net.SecurityProtocolType])
```

If you see `Tls12`, you can euse the following command to force TLS 1.2.

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

If this works, you would need to add this to your PowerShell $PROFILE.

Here is Microsoft's article [How to enable TLS 1.2 on clients](https://learn.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client). Within it, there is a link for an [update](https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392) that may be required.

Also, please be aware that [significant changes](https://twitter.com/TwitterDev/status/1641222782594990080?s=20) to the Twitter API tier access will happen near the end of the month.

**Comment by Saved-by-Him** [comment]
I have done all of this.

In fact I have [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 in my profile since two years ago to resolve an issue with PSGallery.


I've tried:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls13

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls11

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls

Still no luck.... :-(

**Comment by thedavecarroll** [comment]
Immediately after getting the error, run the following command and add the results as a comment.

```powershell
(Get-BluebirdPSHistory -Last 1).ApiResponse.errors
```

**Comment by thedavecarroll** [comment]
Is this a new Twitter dev app? Can you post screenshots of the app from the dev portal? Be careful not to include any keys or secrets.

**Comment by Saved-by-Him** [comment]
Nope. it's a release version I beleive. I installed it from PSGallery through:
PS> Installmodule -Name BluebirdPS -Scope CurrentUser

PS> Get-Module BluebirdPS | fl

Name              : BluebirdPS
Path              : C:\Users\redacted\Documents\PowerShell\Modules\BluebirdPS\0.8.3\BluebirdPS.psm1
Description       : A Twitter Automation Client for PowerShell 7. Tweet, retweet, send direct messages, manage lists, and more.
ModuleType        : Script
Version           : 0.8.3
PreRelease        :
NestedModules     : {BluebirdPS}
ExportedFunctions : {Add-TwitterFriend, Add-TwitterList, Add-TwitterListMember, Add-TwitterListSubscription…}
ExportedCmdlets   :
ExportedVariables :
ExportedAliases   :

**Comment by thedavecarroll** [comment]
Before you can use BluebirdPS, you must create a project and application in the Twitter developer portal - https://developer.twitter.com/en/portal/dashboard

See https://docs.bluebirdps.dev/prerequisites/ to help get you started. 

In case you haven't heard, Twitter will soon (end of this month) change their tiers to Free and Basic.

The Free tier allows you to create a limited number tweets per month. And that is all, no user lookup (other than yourself), no searching for other tweets.

The Basic tier, I believe will be $100 a month.

For details on the Twitter API tiers, see https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api.

I won't be continuing development of BluebirdPS so, even if you do choose to pay Twitter for the Basic tier, the current version will be the last and no bugfixes or new features will be added.

Good luck.

**Comment by Saved-by-Him** [comment]
I already have an App and also a project. My App worked well for almost 5 years. Now Twitter has changed everything and I can no longer interact with it! Why can't I connect to it using my API_Key and my other credentials?

Also, what is that "TLS alert: 'HandshakeFailure'" ?

Thanks.

**Comment by thedavecarroll** [comment]
Due to changes in the Twitter API, no new development will occur for this project.
