### ISSUE TITLE
Special characters in Tweet

### ISSUE THREAD

**Issue by CloudDevDan** [thedavecarroll/BluebirdPS#207]
### What is broken or not working?

Special characters are being rendered by Twitter as '?'. I believe this will have something to do with utf8 encoding. Please see my example in 'What steps will reproduce the behaviour?'

I know it's not a Twitter issue as I can make the post manually and the special characters are rendered as expected.

### PowerShell Environment

```shell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### What steps will reproduce the behavior?

Publish-Tweet -TweetText "Test message: Johan Åhlén & Magnus Mårtensson (livepod)"

On Twitter, this would appear something like: "Test message: Johan ?hl?n & Magnus M?rtensson (livepod)"

**Comment by thedavecarroll** [comment]
Due to changes in the Twitter API, no new development will occur for this project.
