### ISSUE TITLE
Errors on Import-Module

### ISSUE THREAD

**Issue by jdhitsolutions** [thedavecarroll/BluebirdPS#27]
I installed the module from the PowerShell Gallery:

```powershell
install-module bluebirdps -scope allusers
```

But get a number of errors on importing the module.

![image](https://user-images.githubusercontent.com/12089920/99979391-0ac46a00-2d75-11eb-9a13-f84635b54781.png)

On my Windows 10 box I don't have a value for `$env:HOME`.

**Comment by thedavecarroll** [comment]
Thanks for reporting this. I'll publish a fix for it tonight.

**Comment by thedavecarroll** [comment]
@jdhitsolutions 
Considering it's PowerShell 7 and up, do you think this would be sufficient? 

```powershell
if ($IsWindows) {
    $DefaultSavePath = Join-Path -Path $env:USERPROFILE -ChildPath '.BluebirdPS'
} else {
    $DefaultSavePath = Join-Path -Path $env:HOME -ChildPath '.BluebirdPS'
}
```

**Comment by jdhitsolutions** [comment]
I'd think that should be sufficient.
