### ISSUE TITLE
[New Feature] All commands using parameter sets needs default parameter set in cmdletbinding

### ISSUE THREAD

**Issue by jdhitsolutions** [thedavecarroll/BluebirdPS#30]
**Is your feature request related to a problem? Please describe.**
`Get-TwitterUser` has 2 parameter sets. You should define  a default.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I would make the Screenname the default and positional. A user is most likely to run:

```powershell
Get-TwitterUser jeffhicks
```

**Additional context**

**Comment by thedavecarroll** [comment]
Thank you so much for the feedback!

This will be in the next release.

**Comment by thedavecarroll** [comment]
I went through and discovered a few more commands without `DefaultParameterSetName`.

- Get-TwitterUser
- Get-TwitterListSubscriber
- Get-TwitterUserProfileBanner
- Get-TwitterTimeline
- Set-TwitterRateLimitWarning
- Export-TwitterResource

**Comment by jdhitsolutions** [comment]
I think you should also take a look at what parameters make sense as positional parameters.

**Comment by thedavecarroll** [comment]
I've updated or created the following commands to provide `DefaultParameterSetName`.

- Add-TwitterFriend
- Add-TwitterListMember
- Add-TwitterListSubscription
- Get-ErrorCategory
- Get-Tweet
- Get-TweetLikes
- Get-TweetPoll
- Get-TwitterFollowers
- Get-TwitterFriends
- Get-TwitterFriendship
- Get-TwitterList
- Get-TwitterListMember
- Get-TwitterListSubscriber
- Get-TwitterListTweets
- Get-TwitterTimeline
- Publish-Tweet
- Publish-TwitterDM
- Remove-TwitterFriend
- Remove-TwitterList
- Remove-TwitterListMember
- Remove-TwitterListSubscription
- Remove-TwitterSavedSearch
- Set-Retweet
- Set-TweetLike
- Set-TweetReply
- Set-TwitterBlockedUser
- Set-TwitterList
- Set-TwitterMutedUser
- Test-TwitterListMembership
- Test-TwitterListSubscription
- Unpublish-Tweet
- Unpublish-TwitterDM
