### ISSUE TITLE
Set-TwitterAuthentication throws "Cannot find path" error when ~\.BluebirdPS\ does not exist

### ISSUE THREAD

**Issue by jhendricks123** [thedavecarroll/BluebirdPS#69]
**Describe the bug**
After a fresh install of BluebirdPS on a Windows 10 sandbox (2004 (OS build 19041.985) the `Set-TwitterAuthentication` cmdlet throws a Get-ChildItem error when the file ~\.BluebirdPS\twittercred.sav does not already exist.

The folder is still created, and the twittercred.sav file is still created, and follow-up BluebirdPS commands work as expected. Re-running `Set-TwitterAuthentication` when the file exists does not result in an error which is the experience I would expect on the first execution.

**To Reproduce**

Ensure ~\.BluebirdPS\twittercred.sav does not exist, and then run `Set-TwitterAuthentication`

```powershell
C:\Users\WDAGUtilityAccount\Downloads\PowerShell-7.1.3-win-x64> Set-TwitterAuthentication @params
Get-ChildItem: C:\Users\WDAGUtilityAccount\Documents\PowerShell\Modules\bluebirdps\0.5.0\BluebirdPS.psm1:2782
Line |
2782 |  … portDate = (Get-ChildItem -Path $BluebirdPSConfiguration.CredentialsP …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\WDAGUtilityAccount\.BluebirdPS\twittercred.sav' because it does not exist.
```

**Expected behavior**
The ~\.BluebirdPS\ directory is created if it does not exist, and any configuration files that are needed are created without showing warnings or errors to the user.

**PowerShell Environment (please complete the following information):**
 - OS: Windows 10 version 2004 (OS Build 19041.985)
 - PowerShell 7.1.3 x64

**Comment by jhendricks123** [comment]
On line 2782 I changed

```powershell
$BluebirdPSConfiguration.AuthLastExportDate = (Get-ChildItem -Path $BluebirdPSConfiguration.CredentialsPath).LastWriteTime
```

to

```powershell
$BluebirdPSConfiguration.AuthLastExportDate = (Get-ChildItem -Path $BluebirdPSConfiguration.CredentialsPath -ErrorAction Ignore).LastWriteTime ?? (Get-Date)
```

and now I get...

```powershell
PS C:\Users\WDAGUtilityAccount\Downloads\PowerShell-7.1.3-win-x64> Set-TwitterAuthentication @params
WARNING: BluebirdPS configuration file not found. Please run Export-BluebirdPSConfiguration to regenerate.
WARNING: Please use Set-TwitterAuthentication to set the required API keys and secrets. The authentication values will be encrypted and saved to the disk.
```

unless I use `Export-BluebirdPSConfiguration` before Set-TwitterAuthentication - then I get no errors even if twittercred.sav is not present.

**Comment by thedavecarroll** [comment]
Well, that certainly wasn't intended.

Thank you for submitting this issue. I'll work on an update as soon as I can.
