### ISSUE TITLE
Invoke-TwitterRequest - Add option for progress bar for paged requests

### ISSUE THREAD

**Issue by thedavecarroll** [thedavecarroll/BluebirdPS#76]
The command `Invoke-TwitterRequest` will automatically paginate API v1.1 `cursor` and API v2 `pagination_token` and `next_token` (specifically for `Search-Tweet`) based paging requests.

> As a user of BluebirdPS,
> I would like to be made aware of progress during long running, paged requests,
> so that I know the command is still executing.

Create an implementation value that uses `Write-Progress`.

Possible criteria for this functionality:

- After the first paginated call
- After `n` number of calls
- After `n` number of seconds since the first paginated call

A [Twitter poll](https://twitter.com/thedavecarroll/status/1404373754336190464) has been created requesting input for this.

**Comment by RobinDadswell** [comment]
I think the progress bar should track page it's on vs total page if that info is available from the Twitter API. Would probably be the most useful progress bar that can be given then

**Comment by thedavecarroll** [comment]
Unfortunately, I don't believe there is a mechanism to determine the total number of pages a result set may contain.

Great suggestion, though! And thanks for the feedback!

**Comment by thedavecarroll** [comment]
Results of the poll:

```text
Id           : 1404373753925144579
Options      : {1) 1st page:3, 2) nth page:2, 3) n seconds after 1st page:3}
TotalVotes   : 8
Duration     : 2880
EndDateTime  : 6/16/2021 9:42:49 AM
VotingStatus : Closed
```

I was definitely hoping for more votes, or a significant winner. Based on the 8 votes the poll received, it appears there's not a strong opinion on the criteria.

I'll add `Write-Progress` at the beginning of the paging loop.
