### ISSUE TITLE
How Should Rate Limits Be Handled?

### ISSUE THREAD

**Issue by thedavecarroll** [thedavecarroll/BluebirdPS#9]
Virtually all API endpoints have a rate limit, after which you must wait through a reset period.

Currently, there is a module scoped variable, `$RateLimitWarning`, that is set to `$false` when the module is imported.

You can using `Get-TwitterRateLimitWarning` to see if this **Enabled** or **Disabled** and use `Set-TwitterRateLimitWarning` to update the value.

At the moment, this throws a warning like the following prior to reaching the limit.

```console
WARNING: The rate limit for this resource is 15. There are 1 remaining calls to this resource until 10/11/2020 6:18:52 PM.
```

When the rate limit is reached, it will throw a terminating error like the following.

```console
Invoke-TwitterCursorRequest: C:\Program Files\Powershell\7\Modules\Twitter\public\Get-TwitterFollowers.ps1:49
Line |
  49 |          Invoke-TwitterCursorRequest -OAuthParameters $OAuthParameters …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Rate limit of 15 has been reached. Please wait until 10/11/2020 6:18:52 PM before making another attempt for this resource.
```
For cursored and paged requests, the limit could be reached before all items have been returned. The way I have constructed `Invoke-TwitterCursorRequest`, the returned data is handed to the end user after each call. _(At least, it should be working this way.)_ 

`Invoke-TwitterPageRequest` will collect all of the returned data until all pages has been processed or the rate limit for that endpoint is reached, then the entire collection will be returned to the end user.

---
Please vote with the following:
- 👍 Use `Write-Warning` and fail softly
- 👎 Use `Write-Error` and fail at the `Invoke-Twitter*Request` level, but not the function
- ❌ Use `PSCmdLet.ThrowTerminatingError($_)`

Please discuss below.

Thank you.

**Comment by RobinDadswell** [comment]
❌
Personally I think it should be a terminating error as it's not showing you all the data; which could cause considerable issues if you were attempting to pull back some data and do a bit of analysis on it etc.

**Comment by pauby** [comment]
When I run a function to do something, I expect it to do it unless some major went wrong. I don't see a rate limit as something that has gone wrong. I see that as something the function should work around (ie. wait). 

I'm interested to know what this means in practicality:

>  Use Write-Error and fail at the Invoke-Twitter*Request level, but not the functionin what this means

**Comment by scrthq** [comment]
Any option to implement an exponential backoff to handle the rate limit response and ideally not have any data loss (so long as the retry timeframe isn't too far out)?

**Comment by RobinDadswell** [comment]
I guess alternatively just document a maximum returnable data and have that as a hard limit?

**Comment by jdhitsolutions** [comment]
I'd  vote 👍 as the rate limit isn't a problem with *your* code. The command presumably ran but encountered an external obstacle. To me, a warning reminder would suffice. I don't see any reason to throw an exception. If the command was part of larger automated sequence where error handling would be part of the workflow, then I'd make the effort. But my assumption is that most people will use this interactively. But I'm happy to be proven wrong.
